package de.hpi.osm.planpro.generator;

import java.io.BufferedWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;

public class Boilerplate {

	private static String ausgabeFachdatenID = Generator.getRandomUUID();

	public static void generatePrefix(final BufferedWriter writer) throws IOException {
		writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + "\n");
		writer.write(
				"<nsPlanPro:PlanPro_Schnittstelle xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:nsPlanPro=\"http://www.plan-pro.org/modell/PlanPro/1.9.0.2\" xmlns:nsSignalbegriffe_Ril_301=\"http://www.plan-pro.org/modell/Signalbegriffe_Ril_301/1.9.0\">"
						+ "\n");
		writer.write("  <Identitaet>" + "\n");
		writer.write("    <Wert>" + Generator.getRandomUUID() + "</Wert>" + "\n");
		writer.write("  </Identitaet>" + "\n");
		writer.write("  <PlanPro_Schnittstelle_Allg>" + "\n");
		writer.write("    <Erzeugung_Zeitstempel>" + "\n");

		final Instant i = Instant.now();
		final SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");

		writer.write("      <Wert>" + sdf2.format(Date.from(i)) + "</Wert>" + "\n");
		writer.write("    </Erzeugung_Zeitstempel>" + "\n");
		writer.write("    <Werkzeug_Name>" + "\n");
		writer.write("      <Wert>Werkzeugkoffer</Wert>" + "\n");
		writer.write("    </Werkzeug_Name>" + "\n");
		writer.write("    <Werkzeug_Version>" + "\n");
		writer.write("      <Wert>48.3.0</Wert>" + "\n");
		writer.write("    </Werkzeug_Version>" + "\n");
		writer.write("  </PlanPro_Schnittstelle_Allg>" + "\n");
		writer.write("  <LST_Planung>" + "\n");
		writer.write("    <Fachdaten>" + "\n");
		writer.write("      <Ausgabe_Fachdaten>" + "\n");
		writer.write("        <Identitaet>" + "\n");
		writer.write("          <Wert>" + ausgabeFachdatenID + "</Wert>" + "\n");
		writer.write("        </Identitaet>" + "\n");
		writer.write("        <LST_Zustand_Start>" + "\n");
		writer.write("          <Identitaet>" + "\n");
		writer.write("            <Wert>" + Generator.getRandomUUID() + "</Wert>" + "\n");
		writer.write("          </Identitaet>" + "\n");
		writer.write("          <Container/>" + "\n");
		writer.write("        </LST_Zustand_Start>" + "\n");
		writer.write("        <LST_Zustand_Ziel>" + "\n");
		writer.write("          <Identitaet>" + "\n");
		writer.write("            <Wert>" + Generator.getRandomUUID() + "</Wert>" + "\n");
		writer.write("          </Identitaet>" + "\n");
		writer.write("          <Container>" + "\n");
	}

	public static String generateAussenelementansteuerung(final BufferedWriter writer) throws IOException {
		writer.write("            <Aussenelementansteuerung>" + "\n");
		writer.write("                 <Identitaet>" + "\n");
		writer.write("                   <Wert>C35FDB88-889E-539E-A68B-6079265F70D9</Wert>" + "\n");
		writer.write("                 </Identitaet>" + "\n");
		writer.write("                 <Basis_Objekt_Allg>" + "\n");
		writer.write("                   <Datum_Regelwerk>" + "\n");
		writer.write("                     <Wert>2012-02-24</Wert>" + "\n");
		writer.write("                   </Datum_Regelwerk>" + "\n");
		writer.write("                 </Basis_Objekt_Allg>" + "\n");
		writer.write("                 <Objektreferenzen/>" + "\n");
		writer.write("                 <AEA_Allg>" + "\n");
		writer.write("                   <Aussenelementansteuerung_Art>" + "\n");
		writer.write("                     <Wert>ESTW_A</Wert>" + "\n");
		writer.write("                   </Aussenelementansteuerung_Art>" + "\n");
		writer.write("                 </AEA_Allg>" + "\n");
		writer.write("                 <AEA_Energieversorgung>" + "\n");
		writer.write("                   <Energieversorgung_Art_Ersatz>" + "\n");
		writer.write("                     <Wert>Notstromaggregat_NEA_stationaer</Wert>" + "\n");
		writer.write("                   </Energieversorgung_Art_Ersatz>" + "\n");
		writer.write("                   <ID_Energie_Primaer>" + "\n");
		writer.write("                     <Wert>C35FDB88-889E-539E-A68B-6079265F70D9</Wert>" + "\n");
		writer.write("                   </ID_Energie_Primaer>" + "\n");
		writer.write("                 </AEA_Energieversorgung>" + "\n");
		writer.write("                 <Bezeichnung>" + "\n");
		writer.write("                   <Bezeichnung_AEA>" + "\n");
		writer.write("                     <Wert>Scheibenberg</Wert>" + "\n");
		writer.write("                   </Bezeichnung_AEA>" + "\n");
		writer.write("                 </Bezeichnung>" + "\n");
		writer.write("                 <ID_Information_Primaer>" + "\n");
		writer.write("                   <Wert>C35FDB88-889E-539E-A68B-6079265F70D9</Wert>" + "\n");
		writer.write("                 </ID_Information_Primaer>" + "\n");
		writer.write("                 <ID_Unterbringung>" + "\n");
		writer.write("                   <Wert>F4CE3AF8-13B1-4E12-BB4D-982BEA37466E</Wert>" + "\n");
		writer.write("                 </ID_Unterbringung>" + "\n");
		writer.write("            </Aussenelementansteuerung>" + "\n");
		return "C35FDB88-889E-539E-A68B-6079265F70D9";
	}

	public static String generateUnterbringung(final BufferedWriter writer) throws IOException {
		writer.write("               <Unterbringung>" + "\n");
		writer.write("                 <Identitaet>" + "\n");
		writer.write("                   <Wert>F4CE3AF8-13B1-4E12-BB4D-982BEA37466E</Wert>" + "\n");
		writer.write("                 </Identitaet>" + "\n");
		writer.write("                 <Basis_Objekt_Allg>" + "\n");
		writer.write("                   <Datum_Regelwerk>" + "\n");
		writer.write("                     <Wert>2012-02-24</Wert>" + "\n");
		writer.write("                   </Datum_Regelwerk>" + "\n");
		writer.write("                 </Basis_Objekt_Allg>" + "\n");
		writer.write("                 <Objektreferenzen/>" + "\n");
		writer.write("                 <Unterbringung_Allg>" + "\n");
		writer.write("                   <Unterbringung_Art>" + "\n");
		writer.write("                     <Wert>Gebaeude</Wert>" + "\n");
		writer.write("                   </Unterbringung_Art>" + "\n");
		writer.write("                   <Unterbringung_Befestigung>" + "\n");
		writer.write("                     <Wert>Fundament</Wert>" + "\n");
		writer.write("                   </Unterbringung_Befestigung>" + "\n");
		writer.write("                 </Unterbringung_Allg>" + "\n");
		writer.write("                 <ID_GEO_Punkt>" + "\n");
		writer.write(
				"                   <Wert>11314F34-1A1C-4EBB-9AB2-133C5F2A9167</Wert> <!-- Does not exists -->" + "\n");
		writer.write("                 </ID_GEO_Punkt>" + "\n");
		writer.write("               </Unterbringung>" + "\n");
		return "F4CE3AF8-13B1-4E12-BB4D-982BEA37466E";
	}

	public static void generateSuffix(final BufferedWriter writer, final ArrayList<String> uuids) throws IOException {
		writer.write("                  </Container>" + "\n");
		writer.write("        </LST_Zustand_Ziel>" + "\n");
		writer.write("        <Untergewerk_Art>" + "\n");
		writer.write("          <Wert>sonstige</Wert>" + "\n");
		writer.write("        </Untergewerk_Art>" + "\n");
		writer.write("      </Ausgabe_Fachdaten>" + "\n");
		writer.write("    </Fachdaten>" + "\n");
		writer.write("	<Objektmanagement>" + "\n");
		writer.write("		<LST_Planung_Projekt>" + "\n");
		writer.write("			  <Identitaet>" + "\n");
		writer.write("				<Wert>F05DAC3B-4E33-43D3-9A03-6055566FC3B7</Wert>" + "\n");
		writer.write("			  </Identitaet>" + "\n");
		writer.write("			  <LST_Planung_Gruppe>" + "\n");
		writer.write("				<Identitaet>" + "\n");
		writer.write("				  <Wert>AFFE2101-3E72-4D64-88F1-FFE1A69396AA</Wert>" + "\n");
		writer.write("				</Identitaet>" + "\n");
		writer.write("				<Fuehrende_Oertlichkeit>" + "\n");
		writer.write("				  <Wert>ABC</Wert>" + "\n");
		writer.write("				</Fuehrende_Oertlichkeit>" + "\n");
		writer.write("				<LST_Planung_Einzel>" + "\n");
		writer.write("				  <Identitaet>" + "\n");
		writer.write("					<Wert>BE199B7D-A86C-4682-8E08-4B23DE2CF5A3</Wert>" + "\n");
		writer.write("				  </Identitaet>" + "\n");
		writer.write("				  <ID_Ausgabe_Fachdaten>" + "\n");
		writer.write("					<Wert>" + ausgabeFachdatenID + "</Wert>" + "\n");
		writer.write("				  </ID_Ausgabe_Fachdaten>" + "\n");
		writer.write("				  <LST_Objekte_Planungsbereich>" + "\n");

		for (final String uuid : uuids) {
			writer.write("					     <ID_LST_Objekt_Planungsbereich>" + "\n");
			writer.write("							<Wert>" + uuid + "</Wert>" + "\n");
			writer.write("						</ID_LST_Objekt_Planungsbereich>" + "\n");
		}

		writer.write("				  </LST_Objekte_Planungsbereich>" + "\n");
		writer.write("				  <Planung_E_Allg>" + "\n");
		writer.write("					<Bauphase>" + "\n");
		writer.write("					  <Wert>Neubau ESTW-A Scheibenberg</Wert>" + "\n");
		writer.write("					</Bauphase>" + "\n");
		writer.write("					<Bauzustand_Kurzbezeichnung>" + "\n");
		writer.write("					  <Wert>Ibn-Zustand</Wert>" + "\n");
		writer.write("					</Bauzustand_Kurzbezeichnung>" + "\n");
		writer.write("					<Datum_Abschluss_Einzel>" + "\n");
		writer.write("					  <Wert>2015-06-23</Wert>" + "\n");
		writer.write("					</Datum_Abschluss_Einzel>" + "\n");
		writer.write("					<Datum_Regelwerksstand>" + "\n");
		writer.write("					  <Wert>2015-06-23</Wert>" + "\n");
		writer.write("					</Datum_Regelwerksstand>" + "\n");
		writer.write("					<Index_Ausgabe>" + "\n");
		writer.write("					  <Wert>01</Wert>" + "\n");
		writer.write("					</Index_Ausgabe>" + "\n");
		writer.write("					<Informativ>" + "\n");
		writer.write("					  <Wert>false</Wert>" + "\n");
		writer.write("					</Informativ>" + "\n");
		writer.write("					<Laufende_Nummer_Ausgabe>" + "\n");
		writer.write("					  <Wert>04</Wert>" + "\n");
		writer.write("					</Laufende_Nummer_Ausgabe>" + "\n");
		writer.write("					<Planung_E_Art>" + "\n");
		writer.write("					  <Wert>Bauzustand</Wert>" + "\n");
		writer.write("					</Planung_E_Art>" + "\n");
		writer.write("					<Planung_Phase>" + "\n");
		writer.write("					  <Wert>PT_1</Wert>" + "\n");
		writer.write("					</Planung_Phase>" + "\n");
		writer.write("				  </Planung_E_Allg>" + "\n");
		writer.write("				  <Planung_E_Ausgabe_Besonders>" + "\n");
		writer.write("					<Referenz_Vergleich_Besonders>" + "\n");
		writer.write("					  <Wert>12345-67890</Wert>" + "\n");
		writer.write("					</Referenz_Vergleich_Besonders>" + "\n");
		writer.write("					<Vergleich_Ausgabestand_Basis>" + "\n");
		writer.write("					  <Wert>2019-07-31</Wert>" + "\n");
		writer.write("					</Vergleich_Ausgabestand_Basis>" + "\n");
		writer.write("					<Vergleichstyp_Besonders>" + "\n");
		writer.write("					  <Wert>sonstige</Wert>" + "\n");
		writer.write("					</Vergleichstyp_Besonders>" + "\n");
		writer.write("				  </Planung_E_Ausgabe_Besonders>" + "\n");
		writer.write("				  <Planung_E_Handlung>" + "\n");
		writer.write("					<Planung_E_Erstellung>" + "\n");
		writer.write("					  <Identitaet>" + "\n");
		writer.write("						<Wert>1A3E6734-9E68-40FC-8C3F-D231E98146FF</Wert>" + "\n");
		writer.write("					  </Identitaet>" + "\n");
		writer.write("					  <Anhang_Dokumentation>" + "\n");
		writer.write("						  <Identitaet>" + "\n");
		writer.write("							<Wert>1A3E6734-9E68-40FC-8C3F-D23DE98246FF</Wert>" + "\n");
		writer.write("						  </Identitaet>" + "\n");
		writer.write("						  <Anhang_Allg>" + "\n");
		writer.write("							<Anhang_Art>" + "\n");
		writer.write("							  <Wert>Erlaeuterungsbericht</Wert>" + "\n");
		writer.write("							</Anhang_Art>" + "\n");
		writer.write("							<Dateiname>" + "\n");
		writer.write("							  <Wert>Erläuterungsbericht-Scheibenberg</Wert>" + "\n");
		writer.write("							</Dateiname>" + "\n");
		writer.write("							<Dateityp>" + "\n");
		writer.write("							  <Wert>pdf</Wert>" + "\n");
		writer.write("							</Dateityp>" + "\n");
		writer.write("							<Daten>" + "\n");
		writer.write("								<Wert></Wert>" + "\n");
		writer.write("							</Daten>" + "\n");
		writer.write("						  </Anhang_Allg>" + "\n");
		writer.write("						</Anhang_Dokumentation>" + "\n");
		writer.write("					  <Datum>" + "\n");
		writer.write("						<Wert>2015-11-03</Wert>" + "\n");
		writer.write("					  </Datum>" + "\n");
		writer.write("					  <Handelnder>" + "\n");
		writer.write("						<Identitaet>" + "\n");
		writer.write("						  <Wert>60024045-7D4E-4C59-98AC-088D437D4B7A</Wert>" + "\n");
		writer.write("						</Identitaet>" + "\n");
		writer.write("						<Akteur_Allg>" + "\n");
		writer.write("						  <Name_Akteur>" + "\n");
		writer.write("							<Wert>Boockmeyer</Wert>" + "\n");
		writer.write("						  </Name_Akteur>" + "\n");
		writer.write("						  <Name_Akteur_10>" + "\n");
		writer.write("							<Wert>Boockmeyer</Wert>" + "\n");
		writer.write("						  </Name_Akteur_10>" + "\n");
		writer.write("						  <Name_Akteur_5>" + "\n");
		writer.write("							<Wert>Boock</Wert>" + "\n");
		writer.write("						  </Name_Akteur_5>" + "\n");
		writer.write("						</Akteur_Allg>" + "\n");
		writer.write("						<Kontaktdaten>" + "\n");
		writer.write("						  <Identitaet>" + "\n");
		writer.write("							<Wert>55555555-5555-5555-5555-555555555555</Wert>" + "\n");
		writer.write("						  </Identitaet>" + "\n");
		writer.write("						  <Name_Organisation>" + "\n");
		writer.write("							<Wert>HPI-OSM</Wert>" + "\n");
		writer.write("						  </Name_Organisation>" + "\n");
		writer.write("						</Kontaktdaten>" + "\n");
		writer.write("					  </Handelnder>" + "\n");
		writer.write("					  <Ident_Rolle>" + "\n");
		writer.write("						<Wert>Planer</Wert>" + "\n");
		writer.write("					  </Ident_Rolle>" + "\n");
		writer.write("					</Planung_E_Erstellung>" + "\n");
		writer.write("				  </Planung_E_Handlung>" + "\n");
		writer.write("				</LST_Planung_Einzel>" + "\n");
		writer.write("				<Planung_G_Allg>" + "\n");
		writer.write("				  <Datum_Abschluss_Gruppe>" + "\n");
		writer.write("					<Wert>2016-12-31</Wert>" + "\n");
		writer.write("				  </Datum_Abschluss_Gruppe>" + "\n");
		writer.write("				  <PlanPro_XSD_Version>" + "\n");
		writer.write("					<Wert>1.7.0.1</Wert>" + "\n");
		writer.write("				  </PlanPro_XSD_Version>" + "\n");
		writer.write("				  <Untergewerk_Art>" + "\n");
		writer.write("					<Wert>sonstige</Wert>" + "\n");
		writer.write("				  </Untergewerk_Art>" + "\n");
		writer.write("				  <Verantwortliche_Stelle_DB>" + "\n");
		writer.write("					<Wert>DB Netze</Wert>" + "\n");
		writer.write("				  </Verantwortliche_Stelle_DB>" + "\n");
		writer.write("				</Planung_G_Allg>" + "\n");
		writer.write("				<Planung_G_Fuehrende_Strecke>" + "\n");
		writer.write("				  <Strecke_Abschnitt>" + "\n");
		writer.write("					<Wert>Annaberg-Buchholz - Schwarzenberg</Wert>" + "\n");
		writer.write("				  </Strecke_Abschnitt>" + "\n");
		writer.write("				  <Strecke_Km>" + "\n");
		writer.write("					<Wert>120,000</Wert>" + "\n");
		writer.write("				  </Strecke_Km>" + "\n");
		writer.write("				  <Strecke_Nummer>" + "\n");
		writer.write("					<Wert>8980</Wert>" + "\n");
		writer.write("				  </Strecke_Nummer>" + "\n");
		writer.write("				</Planung_G_Fuehrende_Strecke>" + "\n");
		writer.write("				<Planung_G_Schriftfeld>" + "\n");
		writer.write("				  <Bauabschnitt>" + "\n");
		writer.write("					<Wert>Annaberg-Buchholz - Schwarzenberg</Wert>" + "\n");
		writer.write("				  </Bauabschnitt>" + "\n");
		writer.write("				  <Bezeichnung_Anlage>" + "\n");
		writer.write("					<Wert>ESTW-UZ N-Stadt</Wert>" + "\n");
		writer.write("				  </Bezeichnung_Anlage>" + "\n");
		writer.write("				  <Bezeichnung_Planung_Gruppe>" + "\n");
		writer.write("					<Wert>Neubau ESTW-A Scheibenberg</Wert>" + "\n");
		writer.write("				  </Bezeichnung_Planung_Gruppe>" + "\n");
		writer.write("				  <Bezeichnung_Unteranlage>" + "\n");
		writer.write("					<Wert>ESTW-A Scheibenberg</Wert>" + "\n");
		writer.write("				  </Bezeichnung_Unteranlage>" + "\n");
		writer.write("				  <Planungsbuero>" + "\n");
		writer.write("					<Identitaet>" + "\n");
		writer.write("					  <Wert>55555555-5555-5555-5555-555555555555</Wert>" + "\n");
		writer.write("					</Identitaet>" + "\n");
		writer.write("					<Name_Organisation>" + "\n");
		writer.write("					  <Wert>HPI-OSM</Wert>" + "\n");
		writer.write("					</Name_Organisation>" + "\n");
		writer.write("				  </Planungsbuero>" + "\n");
		writer.write("				</Planung_G_Schriftfeld>" + "\n");
		writer.write("				<Polygone_Betrachtungsbereich>" + "\n");
		writer.write("				  <Koordinatensystem_BB>" + "\n");
		writer.write("					<Wert>WGS84</Wert>" + "\n");
		writer.write("				  </Koordinatensystem_BB>" + "\n");
		writer.write("				  <Polygonzug_Betrachtungsbereich>" + "\n");
		writer.write(
				"					<Wert>4541324.55 5647860.25 4533627.31 5629542.69 4530892.30 5615315.52 4530896.25 5615314.81 4535700.32 5625130.79 4541007.74 5647040.74</Wert>"
						+ "\n");
		writer.write("				  </Polygonzug_Betrachtungsbereich>" + "\n");
		writer.write("				</Polygone_Betrachtungsbereich>" + "\n");
		writer.write("				<Polygone_Planungsbereich>" + "\n");
		writer.write("				  <Koordinatensystem_PB>" + "\n");
		writer.write("					<Wert>WGS84</Wert>" + "\n");
		writer.write("				  </Koordinatensystem_PB>" + "\n");
		writer.write("				  <Polygonzug_Planungsbereich>" + "\n");
		writer.write(
				"					<Wert>4534953.69 5631722.21 4535060.27 5631655.77 4534117.81 5629091.17 4534190.47 5629031.56 4534190.47 5626410.63 4534541.42 5626126.37 4534451.48 5625924.01 4533883.87 5626227.30 4533883.87 5625744.61 4533648.18 5624927.37 4533444.84 5624987.20 4533963.42 5627558.05 4533627.31 5629542.69 4533935.67 5628728.88 4533950.34 5629188.21</Wert>"
						+ "\n");
		writer.write("				  </Polygonzug_Planungsbereich>" + "\n");
		writer.write("				</Polygone_Planungsbereich>" + "\n");
		writer.write("			  </LST_Planung_Gruppe>" + "\n");
		writer.write("			  <Planung_P_Allg>" + "\n");
		writer.write("				<Bezeichnung_Planung_Projekt>" + "\n");
		writer.write("				  <Wert>Neubau ESTW Scheibenberg</Wert>" + "\n");
		writer.write("				</Bezeichnung_Planung_Projekt>" + "\n");
		writer.write("				<Datum_Abschluss_Projekt>" + "\n");
		writer.write("				  <Wert>2017-12-31</Wert>" + "\n");
		writer.write("				</Datum_Abschluss_Projekt>" + "\n");
		writer.write("				<Projekt_Nummer>" + "\n");
		writer.write("				  <Wert>1234ABCD5678EFGH</Wert>" + "\n");
		writer.write("				</Projekt_Nummer>" + "\n");
		writer.write("				<Projektleiter>" + "\n");
		writer.write("				  <Identitaet>" + "\n");
		writer.write("					<Wert>3C590A15-5293-4AF6-A81D-1C4E82297602</Wert>" + "\n");
		writer.write("				  </Identitaet>" + "\n");
		writer.write("				  <Akteur_Allg>" + "\n");
		writer.write("					<Name_Akteur>" + "\n");
		writer.write("					  <Wert>Boockmeyer</Wert>" + "\n");
		writer.write("					</Name_Akteur>" + "\n");
		writer.write("					<Name_Akteur_10>" + "\n");
		writer.write("					  <Wert>Boockmeyer</Wert>" + "\n");
		writer.write("					</Name_Akteur_10>" + "\n");
		writer.write("					<Name_Akteur_5>" + "\n");
		writer.write("					  <Wert>Boock</Wert>" + "\n");
		writer.write("					</Name_Akteur_5>" + "\n");
		writer.write("				  </Akteur_Allg>" + "\n");
		writer.write("				  <Kontaktdaten>" + "\n");
		writer.write("					<Identitaet>" + "\n");
		writer.write("					  <Wert>55555555-5555-5555-5555-555555555555</Wert>" + "\n");
		writer.write("					</Identitaet>" + "\n");
		writer.write("					<Name_Organisation>" + "\n");
		writer.write("					  <Wert>HPI-OSM</Wert>" + "\n");
		writer.write("					</Name_Organisation>" + "\n");
		writer.write("				  </Kontaktdaten>" + "\n");
		writer.write("				</Projektleiter>" + "\n");
		writer.write("			  </Planung_P_Allg>" + "\n");
		writer.write("			</LST_Planung_Projekt>" + "\n");
		writer.write("	</Objektmanagement>" + "\n");
		writer.write("  </LST_Planung>" + "\n");
		writer.write("</nsPlanPro:PlanPro_Schnittstelle>" + "\n");
	}
}
